sudo: required
services:
  - docker

before_install:
  - docker build -t aizenbergivan/dockerone -f Dockerfile.dev .

script:
  - docker run -e CI=true aizenbergivan/dockerone npm run test

after_success:
  - docker build -t aizenbergivan/newclient .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push aizenbergivan/newclient
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Newclient"
  env: "Newclient-env"
  bucket_name: "elasticbeanstalk-us-west-2-670787634286"
  bucket_path: "newclient"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"